In [2]:
import numpy as np
import math

# Numpy

## Теория

# Создание массивов 

* Конвертация из Python structures
* Генерация с помощью встроенных функций
* Чтение с диска

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array(((1, 2), (3, 4), (5, 6)))

In [7]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [145]:
d = np.zeros(shape=(3, 4, 5)) # массив из нулей заданной размерности
e = np.ones((5, 5))  # массив с единицами заданной размерности
f = np.empty((4, 4)) # пустой массив со случайными элементами заданной размерности
g = np.linspace(0, 1, 20) # массив значений равномерного разбиения отрезка 0, 1 на 20 значений
g.shape

(20,)

# Размерность и изменение размерности

In [141]:
f.shape

(4, 4)

In [143]:
f = f.reshape((2, -1)) # изменение размерности 
f.shape

(2, 8)

In [144]:
f = f.reshape(-1) # превратить в 1-мерный вектор
f.shape

(16,)

In [150]:
f = f.flatten() # превратить в 1-мерный вектор
f.shape

(16,)

In [152]:
f.reshape((2, -1)) # -1 подставит оставшуюся размерность автоматически
f.reshape((1, 1, -1)).shape # можно добавить "фиктивную" размерность 

(1, 1, 16)

## Индексация 

In [31]:
a = np.arange(30).reshape((2, 3, 5))
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [46]:
print(a[0, :, :]) # 0-ая матрица
print()
print(a[0, 2, :]) # 2 строка "нулевой" матрицы
print()
print(a[0, :, 0]) # 0-ой столбец "первой" матрицы

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[10 11 12 13 14]

[ 0  5 10]


In [49]:
a[0, 0, 1::2]  # 0 строка "нулевой" матрицы срез с 1-ого элемента c шагом 2

array([1, 3])

In [55]:
a[0, 0, 1::2] += 10 # срез - это только вид (view) и его изменение приводит к изменению массива
a

array([[[ 0, 31,  2, 33,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [54]:
b = a[0, 0, 1::2].copy() # создать копию подмассива и работать с ней 
b -= 10
a, b

(array([[[ 0, 21,  2, 23,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14]],
 
        [[15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]]]),
 array([11, 13]))

 ## Практика 1.

1. Создайте массив чисел от 0 до 19 и создайте из него матрицу размерности (4, 5)

2. Выберите срез массива из предыдущего пункта с нечетными столбцами и четными строками. Увеличьте значения элементов среза на 1, не меняя исходный массив.

3. Создайте матрицу:

```array([[ -1.,   0.,  -1.,   0.,  -1.,   0.,  -1.],
       [  0., 777.,   0., 777.,   0., 777.,   0.],
       [ -1.,   0.,  -1.,   0.,  -1.,   0.,  -1.],
       [  0., 777.,   0., 777.,   0., 777.,   0.],
       [ -1.,   0.,  -1.,   0.,  -1.,   0.,  -1.],
       [  0., 777.,   0., 777.,   0., 777.,   0.],
       [ -1.,   0.,  -1.,   0.,  -1.,   0.,  -1.]])
```


## Практика 2

### 1. Подсчет расстояния между векторами (одномерными массивами).

In [79]:
x = np.random.uniform(0, 1, (128))
y = np.random.uniform(0, 1, (128))

In [80]:
def compute_dictance(x, y):
    res = []
    for (x_i, y_i) in zip(x, y):
        res.append((x_i - y_i) ** 2)
    return math.sqrt(sum(res))

In [81]:
np.sqrt(((x - y) ** 2).sum())

4.272934640678457

In [82]:
np.sqrt(((x - y) ** 2).sum()) == compute_dictance(x, y)

False

In [83]:
np.isclose(compute_dictance(x, y), np.sqrt(((x - y) ** 2).sum()))

True

In [84]:
np.linalg.norm((x - y))

4.272934640678457

In [85]:
np.isclose(np.linalg.norm((x - y)), np.sqrt(((x - y) ** 2).sum()))

True

### 2. Broadcasting - сложение матрицы и вектора

In [86]:
A = np.zeros((10, 5))
b = np.random.uniform(size=5)

In [87]:
A.shape, b.shape

((10, 5), (5,))

In [88]:
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
b

array([0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ])

In [90]:
A + b 

array([[0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ],
       [0.03732272, 0.30885064, 0.50313259, 0.09761   , 0.0757133 ]])

Как прибавить вектор к каждому столбцу?

In [91]:
b2 = np.random.uniform(size=10)

In [93]:
A + b2 # исправьте ошибку в коде 

ValueError: operands could not be broadcast together with shapes (10,5) (10,) 

### 3. Умножение вектора на матрицу (матричное умножение).

<img src="https://www.walletfox.com/course/qtconcurrentmatrixvectorSource/matvec1_img.png">

In [94]:
x = np.random.random(size=(5))
A = np.random.random(size=(7, 5))
ax = np.dot(A, x)

In [95]:
ax.shape

(7,)

In [96]:
b = np.random.random(size=(7))
y = np.dot(A, x) + b

In [100]:
x2 = np.random.random(size=(7))
y2 = np.dot(A, x2) # исправьте ошибку в коде так, чтобы можно было посчитать произведение A и х2

ValueError: shapes (7,5) and (7,) not aligned: 5 (dim 1) != 7 (dim 0)

### 4. Stacking нескольких массивов в один массив (batch)

In [101]:
a = np.random.random((10, 10))
a.shape

(10, 10)

In [102]:
list_of_arrays = [np.random.random((10, 10)) for i in range(5)] 
type(list_of_arrays)

list

In [103]:
np.vstack(list_of_arrays).shape

(50, 10)

In [104]:
np.hstack(list_of_arrays).shape

(10, 50)

In [106]:
np.stack(list_of_arrays).shape

(5, 10, 10)

### 5. Stacking нескольких массивов в один массив (разные размерности) (со звездочкой)
в этом случае есть два способа 
- cropping (вырезание) - отрезать от каждого массива, чтобы сделать одинаковую размерность.
- padding (набивка) добавление дополнительных значений по краям.


In [107]:
shapes = np.arange(5, 11)
np.random.choice(shapes)

8

In [108]:
list_of_arrays = [np.random.random((np.random.choice(shapes), np.random.choice(shapes))) for x in range(5)]

In [109]:
[x.shape for x in list_of_arrays]

[(10, 8), (8, 7), (10, 9), (9, 6), (7, 5)]

In [110]:
np.stack(list_of_arrays)

ValueError: all input arrays must have the same shape

In [111]:
min([x.shape[0] for x in list_of_arrays]), min([x.shape[1] for x in list_of_arrays])

(7, 5)

In [112]:
max_shapes = max([x.shape[0] for x in list_of_arrays]), max([x.shape[1] for x in list_of_arrays])
max_shapes

(10, 9)

In [113]:
?np.pad

In [121]:
padded = [np.pad(x, ((0, max_shapes[0] - x.shape[0]), 
                     # write your code here
          for x in list_of_arrays]

SyntaxError: '(' was never closed (1926749898.py, line 1)

In [115]:
result = np.stack(padded)
result.shape

(5, 10, 9)

### 6. Фильтрация

In [116]:
x = np.random.normal(0, 1, (10))
x

array([ 1.22994409,  0.2932342 ,  1.69885841, -1.12668009,  1.23936359,
        0.40931214,  0.4676573 ,  0.03153773,  0.82495781,  0.56745043])

In [117]:
?np.clip

In [118]:
np.abs(x) < 1

array([False,  True, False, False, False,  True,  True,  True,  True,
        True])

In [57]:
x[np.abs(x) < 1] = 1
x

array([ 1.        ,  1.        , -1.30199217,  1.        ,  1.        ,
        1.04565336,  1.        ,  1.        ,  1.        ,  1.        ])

In [58]:
x = np.random.normal(0, 1, (10))
x[~(np.abs(x) >= 1)] = 1
x

array([ 1.        ,  1.        ,  2.57041465, -1.53707931, -1.06222645,
       -2.61284281,  1.        , -1.97770436,  1.        ,  1.        ])

### 7. One hot encoding

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*ggtP4a5YaRx6l09KQaYOnw.png">

In [59]:
colors = ["red", "blue", "green"]
categorical = np.random.choice(colors, size=10)
categorical

array(['blue', 'blue', 'green', 'red', 'red', 'red', 'blue', 'red', 'red',
       'red'], dtype='<U5')

In [60]:
idx_dict = {color: i for i, color in enumerate(colors)}
idx_dict

{'red': 0, 'blue': 1, 'green': 2}

In [67]:
indices = np.array([idx_dict[color] for color in categorical])
indices

array([1, 1, 2, 0, 0, 0, 1, 0, 0, 0])

In [68]:
indices.size

10

In [69]:
b = np.zeros((indices.size, indices.max() + 1))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
b[np.arange(indices.size), indices] = 1 # https://numpy.org/doc/stable/user/basics.indexing.html#integer-array-indexing

In [72]:
b

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [73]:
indices

array([1, 1, 2, 0, 0, 0, 1, 0, 0, 0])

In [74]:
np.arange(indices.size)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 8. Замена nan на среднее значение.

Реализуйте функцию, которая во входной вещественной матрице X находит все значения nan и заменяет их на среднее арифметическое всех остальных элементов. Если все элементы матрицы nan, то верните нулевую матрицу той же размерности.

Например, матрица `np.array([[nan, 1, 2, 3], [4, nan, 5, nan]])` перейдет в `np.array([[3, 1, 2, 3], [4, 3, 5, 3]])`

Подсказка: используйте функцию `np.isnan()` и функцию `np.mean()`

In [126]:
a = np.array([1, 2, 3, np.nan])
(np.isnan(a))

array([False, False, False,  True])

In [128]:
np.any(a) 

True

In [129]:
a[np.isnan(a)] = a[~np.isnan(a)].mean()
a

array([1., 2., 3., 2.])

In [130]:
a[~np.isnan(a)] = np.nan
a

array([nan, nan, nan, nan])

In [131]:
def clean_nans(a: np.array) -> np.array:
    if np.all(np.isnan(a)):
        return np.zeros_like(a)
    a[np.isnan(a)] = a[~np.isnan(a)].mean()
    return a

In [132]:
a = np.arange(10).reshape(5, 2).astype(np.float32)
a[0, 1] = np.nan
a[2, 0] = np.nan
a

array([[ 0., nan],
       [ 2.,  3.],
       [nan,  5.],
       [ 6.,  7.],
       [ 8.,  9.]], dtype=float32)

In [133]:
clean_nans(a)

array([[0., 5.],
       [2., 3.],
       [5., 5.],
       [6., 7.],
       [8., 9.]], dtype=float32)

### 9. Равенство массивов.
Реализуйте функцию, которая на вход принимает два массива first_array и second_array (массивы могут быть n-мерные, разной размерности), а возвращает True если они равны и False - иначе.

In [134]:
a = np.arange(10).reshape(2, 5)
b = np.zeros((2, 5))
b = a.copy() 
# b[0, 1] = 43
a, b

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [135]:
np.all(a == b)

True

In [136]:
np.all((np.isclose(a, b)))

True

### 10. Stacking нескольких массивов в один массив (разные размерности)
Реализуйте совмещение нескольких 2-мерных массивов в один 3-мерный с помощью cropping-a, то есть вырезания из всех массивов наименьшей размерности.

In [137]:
shapes = np.arange(5, 11)
list_of_arrays = [np.random.random((np.random.choice(shapes), np.random.choice(shapes))) for x in range(5)]

In [138]:
a[:min_a, :min_b]

NameError: name 'min_a' is not defined

In [ ]:
# your code here